In [1]:
"""
Test for camera intrinsic and extrinsic

History:
12/07/2022: Created. 
@author: jaerock
"""


'\nTest for camera intrinsic and extrinsic\n\nHistory:\n12/07/2022: Created. \n@author: jaerock\n'

In [2]:

import cv2
import numpy as np


In [3]:
 
# Rotation vector (3x1)
rvec = np.array([0.0249593, -1.5888666, -0.1002387])
 
# Convert to rotation matrix (3x3)
rotation_matrix, _ = cv2.Rodrigues(rvec)
 
# Print the rotation matrix
print(rotation_matrix)
 
# Translate
trans = np.array([1.0249999, 0.8818195, 3.3404123])
# trans.T doesn't work with 1d array
trans = trans.reshape(3, 1)
 
# Transform
transform_matrix = np.append(rotation_matrix, trans, axis=1)
 
# Print the transform matrix
print(transform_matrix)


[[-0.02117208  0.04696295 -0.99867223]
 [-0.07891868  0.99570073  0.04849631]
 [ 0.9966562   0.07984067 -0.0173748 ]]
[[-0.02117208  0.04696295 -0.99867223  1.0249999 ]
 [-0.07891868  0.99570073  0.04849631  0.8818195 ]
 [ 0.9966562   0.07984067 -0.0173748   3.3404123 ]]


In [4]:
 
# Test a rotation
pt_w = np.array([1, 0, 2])
pt_c = np.matmul(rotation_matrix, pt_w.T)
 
print(f"pt_w: {pt_w} --> pt_c: {pt_c}")
 
# Test a transform
pt_w = np.array([1, 0, 2, 1])
pt_c = np.matmul(transform_matrix, pt_w.T)
 
print(f"pt_w: {pt_w} --> pt_c: {pt_c}")


pt_w: [1 0 2] --> pt_c: [-2.01851654  0.01807394  0.9619066 ]
pt_w: [1 0 2 1] --> pt_c: [-0.99351664  0.89989344  4.3023189 ]


In [5]:
 
# ---------------------------------------------------------------
# ---------------------------------------------------------------
# Test a projection
f = 632.86136
cx = 328.65439
cy = 243.59555
 


In [6]:
# ---------------------------------------------------------------
# Method 1
camera_matrix = np.array([[f, 0, cx], 
                          [0, f, cy],
                          [0, 0, 1]])
print(f"camera_matrix:\n{camera_matrix}")
 
projection_matrix = np.matmul(camera_matrix, transform_matrix)
print(f"projection_matrix:\n{projection_matrix}")
 
#pt_w = np.array([1, 0, 2, 1])
pt_w = np.array([0, 0, 0, 1]) # world origin
pt_i = np.matmul(projection_matrix, pt_w.T)
s = pt_i[2] # not sure about this
u = pt_i[0]/s
v = pt_i[1]/s
 
print(f"pt_w: {pt_w} --> pt_i: {pt_i}")
print(f"pt_w: {pt_w} --> u, v: {u}, {v}")


camera_matrix:
[[632.86136   0.      328.65439]
 [  0.      632.86136 243.59555]
 [  0.        0.        1.     ]]
projection_matrix:
[[ 3.14156445e+02  5.59610232e+01 -6.37731370e+02  1.74652400e+03]
 [ 1.92836429e+02  6.49589351e+02  2.64590169e+01  1.37177906e+03]
 [ 9.96656202e-01  7.98406666e-02 -1.73747999e-02  3.34041230e+00]]
pt_w: [0 0 0 1] --> pt_i: [1746.52399752 1371.77905949    3.3404123 ]
pt_w: [0 0 0 1] --> u, v: 522.8468346613563, 410.6615999138145


In [7]:

# ---------------------------------------------------------------
# Method 2
# What if pt_c[2] is zero? 
#pt_w = np.array([1, 0, 2, 1])
pt_w = np.array([0, 0, 0, 1]) # world origin
pt_c = np.matmul(transform_matrix, pt_w.T)
u = f * pt_c[0]/pt_c[2] + cx
v = f * pt_c[1]/pt_c[2] + cy
 
print(f"pt_w: {pt_w} --> pt_c: {pt_c}")
print(f"pt_w: {pt_w} --> u, v: {u}, {v}")


pt_w: [0 0 0 1] --> pt_c: [1.0249999 0.8818195 3.3404123]
pt_w: [0 0 0 1] --> u, v: 522.8468346613563, 410.6615999138145
